version: '3'

services:

  node:
    image: kevinlimak10/node:latest
    container_name: node
    networks:
      - nodenet

  nginx: 
    image: kevinlimak10/nginx:latest
    container_name: nginx
    networks: 
      - nodenet
    ports:
      - 8080:80
      - 3306:3306
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./mysql:../mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet
    
networks:
  nodenet:
    driver: bridge